### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by Cretezy** [Nuytemans-Dieter/ConfigAPI#1]
Hey, nice library, saw it on Spigot.

One issue that may arrise is the use of a public domain license. Some coutries (like Germany) don't reconize public domain licenses and can cause issues.

Using a "real" but very permissible license is better in this case.

See https://choosealicense.com/ for more information on licensing choises. MIT is probably most aligned with your idea.

See https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense why Unlicensed may cause issues.

**Comment by Nuytemans-Dieter** [comment]
Hey, thank you!

I was completely unaware of this, thank you for letting me know. I will take care of this issue today.

Cheers, man!
